### ISSUE TITLE
The link to the ACM console is not shown in OCP web ui

### ISSUE THREAD

**Issue by e-minguez** [stolostron/console-chart#177]
![image](https://user-images.githubusercontent.com/346758/148761115-4eefe05d-be61-4dd0-82d3-17a948ccd2d0.png)

Tried on a different browser, incognito, restarting the OpenShift console pods (`oc delete pod -l component=ui -n openshift-console`) as well as the console-operator pod with no luck

**Comment by KevinFCormier** [comment]
Starting with I believe OCP 4.8, instead of showing in the application switcher, it will show in the perspective switcher at the top of the left-hand navigation menu.
